export const languageMap: { [key: string]: string } = {
  en: "English",
  uk: "Українська",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  it: "Italiano",
  pt: "Português",
  nl: "Nederlands",
  pl: "Polski",
  tr: "Türkçe",
  hi: "हिन्दी",
  ko: "한국어",
  ja: "日本語",
  ar: "العربية",
  fa: "فارسی",
  vi: "Tiếng Việt",
  el: "Ελληνικά",
  cs: "Čeština",
  bg: "Български",
  sv: "Svenska",
  fi: "Suomi",
  hu: "Magyar",
};